# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # install bazel
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Unpack KSP libraries
        uses: edgarrc/action-7z@v1
        with:
          args: 7z x lib/KSP_Data-1.12.3.7z -p${{secrets.BIN_PWD}} -olib/ksp
      - name: Setup lib directory
        run: |
          sudo chown -R $(id -un) lib/ksp
          sudo chmod -R 755 lib/ksp
          ln -s /lib/mono/4.5/ lib/mono-4.5
          echo "contents of mono-4.5"
          ls lib/mono-4.5
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-complete python-setuptools python3-virtualenv python3-dev autoconf libtool luarocks texlive-latex-base texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra libxml2-dev libxslt1-dev librsvg2-bin libenchant1c2a latexmk
      - name: Run bazel
        run: bazel build //:krpc
      - name: Copy built zip file
        run: cp bazel-bin/krpc-*.zip .
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: krpc
          path: krpc-*.zip
